export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PLATFORM_ROUTE = '/'
export const TOURNAMENT_ROUTE = '/tournament'
export const PROFILE_ROUTE = '/profile'
